### PR TITLE
Documentation spelling errors fixed

### PR DESCRIPTION
**Pull request by timgifford**

### CODE REVIEW

**Comment by michaelsembwever** [comment]
looks good @timgifford 
i'll push these through soon.

**Comment by michaelsembwever** [comment]
this has been merged manually if you'd like to check and close.

**Comment by timgifford** [comment]
Looks good! Thanks

**Comment by arhoads** [comment]
These changes are not reflected on the website currently. https://tiles.apache.org/framework/tutorial/advanced/nesting-extending.html

**Comment by michaelsembwever** [comment]
@arhoads @timgifford all good and published now.

**Pull request closed without merging**
